### ISSUE TITLE
Request textDocument/hover failed when in monorepro

### ISSUE THREAD

**Issue by pattrickrice** [johnsoncodehk/volar#1025]
Hi there, I created a project in a nested directory using `npm init vue@latest`. After install, it seems like Volar just crashes when trying to hover over symbols in .vue files. This does not occur when opening the directory as the root. I cannot provide a repro, sorry

```console
<--- Last few GCs --->

[9865:0x47cb350]    46574 ms: Mark-sweep (reduce) 4093.0 (4105.5) -> 4092.8 (4105.5) MB, 2579.8 / 0.0 ms  (average mu = 0.098, current mu = 0.001) allocation failure scavenge might not succeed
[9865:0x47cb350]    48664 ms: Mark-sweep (reduce) 4093.8 (4102.5) -> 4093.3 (4103.8) MB, 2086.4 / 0.0 ms  (average mu = 0.051, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa04200 node::Abort() [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
 2: 0x94e4e9 node::FatalError(char const*, char const*) [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
 3: 0xb7978e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
 4: 0xb79b07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
 5: 0xd34395  [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
 6: 0xd34f1f  [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
 7: 0xd42fab v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
 8: 0xd46b6c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
 9: 0xd1524b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
10: 0x105b23f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
11: 0x1401219  [/home/price/.vscode-server/bin/b5205cc8eb4fbaa726835538cd82372cc0222d43/node]
[Info  - 8:39:01 AM] Connection to server got closed. Server will restart.
[Error - 8:39:01 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5782:25)
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:11292:35)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13647:38)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:16847:15)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13635:16)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5007:24)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at IPCMessageReader.fireClose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4414:27)
	at ChildProcess.<anonymous> (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:6049:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[Error - 8:39:01 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5782:25)
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:11292:35)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13647:38)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:16847:15)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13635:16)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5007:24)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at IPCMessageReader.fireClose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4414:27)
	at ChildProcess.<anonymous> (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:6049:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[Error - 8:39:01 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5782:25)
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:11292:35)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13647:38)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:16847:15)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13635:16)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5007:24)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at IPCMessageReader.fireClose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4414:27)
	at ChildProcess.<anonymous> (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:6049:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[Error - 8:39:01 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5782:25)
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:11292:35)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13647:38)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:16847:15)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13635:16)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5007:24)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at IPCMessageReader.fireClose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4414:27)
	at ChildProcess.<anonymous> (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:6049:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[Error - 8:39:01 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5782:25)
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:11292:35)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13647:38)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:16847:15)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13635:16)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5007:24)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at IPCMessageReader.fireClose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4414:27)
	at ChildProcess.<anonymous> (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:6049:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
[Error - 8:39:01 AM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5782:25)
	at Object.dispose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:11292:35)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13647:38)
	at LanguageClient.handleConnectionClosed (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:16847:15)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:13635:16)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at closeHandler (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:5007:24)
	at CallbackList.invoke (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4221:35)
	at Emitter.fire (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4272:34)
	at IPCMessageReader.fireClose (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:4414:27)
	at ChildProcess.<anonymous> (/home/price/.vscode-server/extensions/johnsoncodehk.volar-0.32.1/out/node/client.js:6049:45)
	at ChildProcess.emit (events.js:327:22)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

```

**Comment by johnsoncodehk** [comment]
Seems it just out of memory on your project, please don't open the monorepo at root on vscode, try enable `"volar.lowPowerMode": true`, and please track #1108.

**Comment by pattrickrice** [comment]
Low power mode doesn't have an effect

**Comment by pattrickrice** [comment]
Fwiw I'm continuing to use vetur until this issue is resolved.

**Comment by johnsoncodehk** [comment]
This problem is usually just caused by your tsconfig/jsconfig including too many things unnecessarily, but I can't even confirm this without a repro case. "opening the directory as the root" is the only solution for you due to information is missing.
