### ISSUE TITLE
[vue-tsc] Cannot find module 'typescript/lib/tsc'

### ISSUE THREAD

**Issue by Gercov** [johnsoncodehk/volar#1149]
I was trying reinstall typescript also all node_modules folder, but it dont help 

```
$ vue-tsc --noEmit
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'typescript/lib/tsc'
Require stack:
- C:\Users\Александр\AppData\Roaming\npm\node_modules\vue-tsc\bin\vue-tsc.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.resolve (internal/modules/cjs/helpers.js:99:19)←[39m
    at Object.<anonymous> (C:\Users\Александр\AppData\Roaming\npm\node_modules\←[4mvue-tsc←[24m\bin\vue-tsc.js:5:25)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m

←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\Александр\\AppData\\Roaming\\npm\\node_modules\\vue-tsc\\bin\\vue-tsc.js'←[39m
  ]
}
```

**Comment by xiaoxiangmoe** [comment]
Can you provide me a reproduction repo？

**Comment by Gercov** [comment]
> Can you provide me a reproduction repo？

I'm solved problem this error, now my console see like: 
![image](https://user-images.githubusercontent.com/51914212/162264333-99aa5491-e316-4bf3-b21c-5bc50c6d650d.png)

**Comment by Gercov** [comment]
@xiaoxiangmoe i send invite to repo

**Comment by xiaoxiangmoe** [comment]
It would be great if you can reproduce it in https://github.com/johnsoncodehk/volar-starter

**Comment by Gercov** [comment]
@xiaoxiangmoe do you mean i clone and run that?

**Comment by xiaoxiangmoe** [comment]
Yes

**Comment by Gercov** [comment]
> Yes

It's work, but why my past don't work?

**Comment by xiaoxiangmoe** [comment]
Can you try to reproduce it in new repo? Copy some code that may cause error, and run it.
