### ISSUE TITLE
Volar extension crashes when i a "div" element in Vuejs template

### ISSUE THREAD

**Issue by murugappanrm** [johnsoncodehk/volar#1171]
Hi,

The VS Code Volar Extension crashes when i add a "div" element inside a vuejs 3 template. After that the emmet does not work in vue files anymore.

```
<template>
  <NavBar></NavBar>
  <router-view></router-view>
  <div>
    <div>
      <p></p>
    </div>
  </div>
  **div**
</template>
```
The VS Code version is:

```
Version: 1.66.1 (user setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043

```
Volar Extension version is 

```
Name: Vue Language Features (Volar)
Id: johnsoncodehk.volar
Description: Language support for Vue 3
Version: 0.34.5
Publisher: Johnson Chu
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar

The errror messages are: 

```

![Screenshot_1](https://user-images.githubusercontent.com/63133893/162761790-15277687-bbfb-43f8-be30-5ef936c7a170.png)

Now is  using this extension which works but the emmet is not working properly when i add class:
```

Name: Test Patched Extension 1
Id: zardoy.testPatched1
Description: Volar with better support for Vue2
Version: 0.33.13
Publisher: zardoy
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=zardoy.testPatched1


```

**Comment by NathanVG** [comment]
I have the same issue, but it happens immediately when it wants to suggest a tag: 
<img width="453" alt="image" src="https://user-images.githubusercontent.com/3620183/162829421-4e4136c9-e084-48fa-ac22-8e5d46b14f66.png">

```
load volar.config.js failed in /Users/xxxxx/Documents/dev/Personal/xxxx
[Error - 10:52:20 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Could not find source file: '/Users/xxxxx/Documents/dev/Personal/xxxx/src/pages/dashboard/index.vue.__VLS_template.tsx'.
  Code: -32603 
/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:162200
                var error = new Error("Could not find source file: '".concat(fileName, "'."));
                            ^

Error: Could not find source file: '/Users/xxxxx/Documents/dev/Personal/xxxx/src/pages/dashboard/index.vue.__VLS_template.tsx'.
    at getValidSourceFile (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:162200:29)
    at Object.getCompletionsAtPosition (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typescript.js:162483:80)
    at c (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:1280:6283)
    at a (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:1280:1837)
    at async Object.doComplete (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:1272:10225)
    at async /Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:1164:16529
    at async Aoe (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:1133:3448)
    at async Object.<anonymous> (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:1164:16161) {
  ProgramFiles: [
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es5.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2016.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2019.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2020.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2021.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2022.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.esnext.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.core.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.collection.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.generator.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.iterable.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.promise.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.proxy.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.reflect.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2016.array.include.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.object.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.string.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.intl.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.asyncgenerator.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.asynciterable.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.intl.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.promise.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2018.regexp.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2019.array.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2019.object.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2019.string.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2019.symbol.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2020.bigint.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2020.promise.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2020.sharedmemory.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2020.string.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2020.symbol.wellknown.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2020.intl.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2021.promise.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2021.string.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2021.weakref.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2021.intl.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2022.array.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2022.error.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2022.object.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.es2022.string.d.ts',
    '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/lib.esnext.intl.d.ts',
    '/Users/xxxxx/Documents/dev/Personal/qguard/node_modules/@babel/types/lib/index.d.ts',
    '/Users/xxxxx/Documents/dev/Personal/qguard/node_modules/@vue/shared/dist/shared.d.ts',
    '/Users/n.van.gierdeg[Info  - 10:52:20 PM] Connection to server got closed. Server will restart.
load volar.config.js failed in /Users/xxxxx/Documents/dev/Personal/xxxx
[Error - 10:52:21 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:52:21 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:52:21 PM] Request textDocument/documentLink failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:4
${JSON.stringify(ae.error,void 0,4)}`):i.error("Received response message without id. No further error information provided.");else{let Ce=ae.id,qe=y.get(Ce);if(De(ae,qe),qe!==void 0){y.delete(Ce);try{if(ae.error){let Re=ae.error;qe.reject(new Lt.ResponseError(Re.code,Re.message,Re.data))}else if(ae.result!==void 0)qe.resolve(ae.result);else throw new Error("Should never happen.")}catch(Re){Re.message?i.error(`Response handler '${qe.method}' failed with message: ${Re.message}`):i.error(`Response handler '${qe.method}' failed unexpectedly.`)}}}}function ue(ae){if(Z())return;let Ce,qe;if(ae.method===M1.type.method){let Re=ae.params.id;v.delete(Re),ge(ae);return}else{let Re=f.get(ae.method);Re&&(qe=Re.handler,Ce=Re.type)}if(qe||p)try{if(ge(ae),qe)if(ae.params===void 0)Ce!==void 0&&Ce.numberOfParams!==0&&Ce.parameterStructures!==Lt.ParameterStructures.byName&&i.error(`Notification ${ae.method} defines ${Ce.numberOfParams} params but received none.`),qe();else if(Array.isArray(ae.params)){let Re=ae.params;ae.method===L1.type.method&&Re.length===2&&zB.is(Re[0])?qe({token:Re[0],value:Re[1]}):(Ce!==void 0&&(Ce.parameterStructures===Lt.ParameterStructures.byName&&i.error(`Notification ${ae.method} defines parameters by name but received parameters by position`),Ce.numberOfParams!==ae.params.length&&i.error(`Notification ${ae.method} defines ${Ce.numberOfParams} params but received ${Re.length} arguments`)),qe(...Re))}else Ce!==void 0&&Ce.parameterStructures===Lt.ParameterStructures.byPosition&&i.error(`Notification ${ae.method} defines parameters by position but received parameters by name`),qe(ae.params);else p&&p(ae.method,ae.params)}catch(Re){Re.message?i.error(`Notification handler '${ae.method}' failed with message: ${Re.message}`):i.error(`Notification handler '${ae.method}' failed unexpectedly.`)}else T.fire(ae)}function pe(ae){if(!ae){i.error("Received empty message.");return}i.error(`Received message which is neither a response nor a notification message:
                                                                                                                                                                                                                                                ^

D1 [Error]: Unhandled method volar/getAttrNameCaseClient
    at ee (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:4:241)
    at ce (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:3:6736)
    at Immediate.<anonymous> (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:3:6577)
    at processImmediate (node:internal/timers:464:21) {
  code: -32601,
  data: undefined
}
[Info  - 10:52:21 PM] Connection to server got closed. Server will restart.
[Error - 10:52:21 PM] Request textDocument/semanticTokens/range failed.
Error: Connection got disposed.
    at Object.dispose (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:29:4524)
    at Object.dispose (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:34:10441)
    at Dx.handleConnectionClosed (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:36:10580)
    at Dx.handleConnectionClosed (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:39:48692)
    at t (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:36:10288)
    at j0.invoke (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:2:14382)
    at Nc.fire (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:2:15151)
    at W (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:3:6340)
    at j0.invoke (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:2:14382)
    at Nc.fire (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:2:15151)
    at lb.fireClose (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:2:17406)
    at ChildProcess.<anonymous> (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/client.js:29:12844)
    at ChildProcess.emit (node:events:402:35)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
load volar.config.js failed in /Users/xxxxx/Documents/dev/Personal/xxxx
[Error - 10:52:21 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:52:21 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:52:21 PM] Request textDocument/documentLink failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:4
${JSON.stringify(ae.error,void 0,4)}`):i.error("Received response message without id. No further error information provided.");else{let Ce=ae.id,qe=y.get(Ce);if(De(ae,qe),qe!==void 0){y.delete(Ce);try{if(ae.error){let Re=ae.error;qe.reject(new Lt.ResponseError(Re.code,Re.message,Re.data))}else if(ae.result!==void 0)qe.resolve(ae.result);else throw new Error("Should never happen.")}catch(Re){Re.message?i.error(`Response handler '${qe.method}' failed with message: ${Re.message}`):i.error(`Response handler '${qe.method}' failed unexpectedly.`)}}}}function ue(ae){if(Z())return;let Ce,qe;if(ae.method===M1.type.method){let Re=ae.params.id;v.delete(Re),ge(ae);return}else{let Re=f.get(ae.method);Re&&(qe=Re.handler,Ce=Re.type)}if(qe||p)try{if(ge(ae),qe)if(ae.params===void 0)Ce!==void 0&&Ce.numberOfParams!==0&&Ce.parameterStructures!==Lt.ParameterStructures.byName&&i.error(`Notification ${ae.method} defines ${Ce.numberOfParams} params but received none.`),qe();else if(Array.isArray(ae.params)){let Re=ae.params;ae.method===L1.type.method&&Re.length===2&&zB.is(Re[0])?qe({token:Re[0],value:Re[1]}):(Ce!==void 0&&(Ce.parameterStructures===Lt.ParameterStructures.byName&&i.error(`Notification ${ae.method} defines parameters by name but received parameters by position`),Ce.numberOfParams!==ae.params.length&&i.error(`Notification ${ae.method} defines ${Ce.numberOfParams} params but received ${Re.length} arguments`)),qe(...Re))}else Ce!==void 0&&Ce.parameterStructures===Lt.ParameterStructures.byPosition&&i.error(`Notification ${ae.method} defines parameters by position but received parameters by name`),qe(ae.params);else p&&p(ae.method,ae.params)}catch(Re){Re.message?i.error(`Notification handler '${ae.method}' failed with message: ${Re.message}`):i.error(`Notification handler '${ae.method}' failed unexpectedly.`)}else T.fire(ae)}function pe(ae){if(!ae){i.error("Received empty message.");return}i.error(`Received message which is neither a response nor a notification message:
                                                                                                                                                                                                                                                ^

D1 [Error]: Unhandled method volar/getAttrNameCaseClient
    at ee (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:4:241)
    at ce (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:3:6736)
    at Immediate.<anonymous> (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:3:6577)
    at processImmediate (node:internal/timers:464:21) {
  code: -32601,
  data: undefined
}
[Info  - 10:52:21 PM] Connection to server got closed. Server will restart.
load volar.config.js failed in /Users/xxxxx/Documents/dev/Personal/xxxx
[Error - 10:52:22 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:52:22 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:52:22 PM] Request textDocument/documentLink failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:4
${JSON.stringify(ae.error,void 0,4)}`):i.error("Received response message without id. No further error information provided.");else{let Ce=ae.id,qe=y.get(Ce);if(De(ae,qe),qe!==void 0){y.delete(Ce);try{if(ae.error){let Re=ae.error;qe.reject(new Lt.ResponseError(Re.code,Re.message,Re.data))}else if(ae.result!==void 0)qe.resolve(ae.result);else throw new Error("Should never happen.")}catch(Re){Re.message?i.error(`Response handler '${qe.method}' failed with message: ${Re.message}`):i.error(`Response handler '${qe.method}' failed unexpectedly.`)}}}}function ue(ae){if(Z())return;let Ce,qe;if(ae.method===M1.type.method){let Re=ae.params.id;v.delete(Re),ge(ae);return}else{let Re=f.get(ae.method);Re&&(qe=Re.handler,Ce=Re.type)}if(qe||p)try{if(ge(ae),qe)if(ae.params===void 0)Ce!==void 0&&Ce.numberOfParams!==0&&Ce.parameterStructures!==Lt.ParameterStructures.byName&&i.error(`Notification ${ae.method} defines ${Ce.numberOfParams} params but received none.`),qe();else if(Array.isArray(ae.params)){let Re=ae.params;ae.method===L1.type.method&&Re.length===2&&zB.is(Re[0])?qe({token:Re[0],value:Re[1]}):(Ce!==void 0&&(Ce.parameterStructures===Lt.ParameterStructures.byName&&i.error(`Notification ${ae.method} defines parameters by name but received parameters by position`),Ce.numberOfParams!==ae.params.length&&i.error(`Notification ${ae.method} defines ${Ce.numberOfParams} params but received ${Re.length} arguments`)),qe(...Re))}else Ce!==void 0&&Ce.parameterStructures===Lt.ParameterStructures.byPosition&&i.error(`Notification ${ae.method} defines parameters by position but received parameters by name`),qe(ae.params);else p&&p(ae.method,ae.params)}catch(Re){Re.message?i.error(`Notification handler '${ae.method}' failed with message: ${Re.message}`):i.error(`Notification handler '${ae.method}' failed unexpectedly.`)}else T.fire(ae)}function pe(ae){if(!ae){i.error("Received empty message.");return}i.error(`Received message which is neither a response nor a notification message:
                                                                                                                                                                                                                                                ^

D1 [Error]: Unhandled method volar/getAttrNameCaseClient
    at ee (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:4:241)
    at ce (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:3:6736)
    at Immediate.<anonymous> (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:3:6577)
    at processImmediate (node:internal/timers:464:21) {
  code: -32601,
  data: undefined
}
[Info  - 10:52:22 PM] Connection to server got closed. Server will restart.
load volar.config.js failed in /Users/xxxxx/Documents/dev/Personal/xxxx
[Error - 10:52:22 PM] Request textDocument/completion failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:52:22 PM] Request textDocument/codeAction failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
[Error - 10:52:22 PM] Request textDocument/documentLink failed.
  Message: Unhandled method volar/getAttrNameCaseClient
  Code: -32601 
/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:4
${JSON.stringify(ae.error,void 0,4)}`):i.error("Received response message without id. No further error information provided.");else{let Ce=ae.id,qe=y.get(Ce);if(De(ae,qe),qe!==void 0){y.delete(Ce);try{if(ae.error){let Re=ae.error;qe.reject(new Lt.ResponseError(Re.code,Re.message,Re.data))}else if(ae.result!==void 0)qe.resolve(ae.result);else throw new Error("Should never happen.")}catch(Re){Re.message?i.error(`Response handler '${qe.method}' failed with message: ${Re.message}`):i.error(`Response handler '${qe.method}' failed unexpectedly.`)}}}}function ue(ae){if(Z())return;let Ce,qe;if(ae.method===M1.type.method){let Re=ae.params.id;v.delete(Re),ge(ae);return}else{let Re=f.get(ae.method);Re&&(qe=Re.handler,Ce=Re.type)}if(qe||p)try{if(ge(ae),qe)if(ae.params===void 0)Ce!==void 0&&Ce.numberOfParams!==0&&Ce.parameterStructures!==Lt.ParameterStructures.byName&&i.error(`Notification ${ae.method} defines ${Ce.numberOfParams} params but received none.`),qe();else if(Array.isArray(ae.params)){let Re=ae.params;ae.method===L1.type.method&&Re.length===2&&zB.is(Re[0])?qe({token:Re[0],value:Re[1]}):(Ce!==void 0&&(Ce.parameterStructures===Lt.ParameterStructures.byName&&i.error(`Notification ${ae.method} defines parameters by name but received parameters by position`),Ce.numberOfParams!==ae.params.length&&i.error(`Notification ${ae.method} defines ${Ce.numberOfParams} params but received ${Re.length} arguments`)),qe(...Re))}else Ce!==void 0&&Ce.parameterStructures===Lt.ParameterStructures.byPosition&&i.error(`Notification ${ae.method} defines parameters by position but received parameters by name`),qe(ae.params);else p&&p(ae.method,ae.params)}catch(Re){Re.message?i.error(`Notification handler '${ae.method}' failed with message: ${Re.message}`):i.error(`Notification handler '${ae.method}' failed unexpectedly.`)}else T.fire(ae)}function pe(ae){if(!ae){i.error("Received empty message.");return}i.error(`Received message which is neither a response nor a notification message:
                                                                                                                                                                                                                                                ^

D1 [Error]: Unhandled method volar/getAttrNameCaseClient
    at ee (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:4:241)
    at ce (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:3:6736)
    at Immediate.<anonymous> (/Users/xxxxx/.vscode/extensions/johnsoncodehk.volar-0.34.5-darwin-arm64/dist/node/server.js:3:6577)
    at processImmediate (node:internal/timers:464:21) {
  code: -32601,
  data: undefined
}
[Error - 10:52:22 PM] The Volar - Language Features Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by johnsoncodehk** [comment]
You could add `"allowJs": true` to tsconfig as quick fix.

**Comment by NathanVG** [comment]
I just get more errors if I do that: 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/3620183/162833307-3e2132c5-94ca-4c33-aa3a-b10880358b37.png">

**Comment by johnsoncodehk** [comment]
@NathanVG please also add `"jsx": "preserve"`.

**Comment by murugappanrm** [comment]
@johnsoncodehk ,

I am not familiar with what you are asking to do. I do not have tsconfig. Where is that in vscode? Appreciate a clearer advice, please. Thank you.

**Comment by NathanVG** [comment]
@johnsoncodehk That fixed it, thank you!

**Comment by johnsoncodehk** [comment]
@murugappanrm so do you have jsconfig? If you don't have any tsconfig / jsconfig, you should not have this error.

You can find current vue document tsconfig from status bar.

<img width="131" alt="image" src="https://user-images.githubusercontent.com/16279759/162837288-25d0adae-bcf2-46a1-9ea8-cd3d0f914464.png">

**Comment by murugappanrm** [comment]
@NathanVG @johnsoncodehk 

Instead doing that. i prefer using this extension "zardoy.testPatched1" temporarily. This extension works perfectly, for now.

**Comment by jaredplowman** [comment]
Can confirm also having the same issue, this issue is not present in v33.10 so I have rolled back for now.

**Comment by murugappanrm** [comment]
@wgyy @jaredplowman 

Until Johnson resolves the issue. suggest you uninstall volar extension and install this one  "zardoy.testPatched1". It works perfectly the same as Volar and also supports Vue 2 and 3. The emmet also works very well now. 

@johnsoncodehk with the alternative extension  "zardoy.testPatched1" i did not have to meddle with settings. Thank you anyway, please inform us when the issue is fixed.

**Comment by tiger-githubb** [comment]
i have this problem to i can't solve it
