### ISSUE TITLE
vue-tsc  build  error

### ISSUE THREAD

**Issue by hxzAugustinus** [johnsoncodehk/volar#1200]
```bash
+ rm -rf 'dist/*'
+ node -v
v13.12.0
+ npm run build:test
> vue-tsc --noEmit && vite build --mode test

*/node_modules/vue-tsc/out/proxy.js:38
    const tsRuntime = options.oldProgram?.__VLS_tsRuntime ?? (0, vue_typescript_1.createTypeScriptRuntime)({
                                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.createProgram (*/node_modules/typescript/lib/tsc.js:94485:118)
    at performCompilation (*/node_modules/typescript/lib/tsc.js:102895:26)
    at executeCommandLineWorker (*/node_modules/typescript/lib/tsc.js:102780:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

 info:
node   v13.12.0 ; 
vue-tsc   0.33.9

**Comment by xiaoxiangmoe** [comment]
try to update node version to 16

**Comment by hxzAugustinus** [comment]
thanks, it't   ok
