### ISSUE TITLE
Request textDocument/semanticTokens/range failed.

### ISSUE THREAD

**Issue by JJLau626** [johnsoncodehk/volar#1271]
Sometime I open VSCode would show up the message.

and the output are follow there

`
[Error - 09:16:00] Request textDocument/semanticTokens/range failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:29:4524)
    at Object.dispose (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:34:10441)
    at Lx.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:36:10580)
    at Lx.handleConnectionClosed (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:39:48692)
    at t (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:36:10288)
    at U0.invoke (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:2:14382)
    at Lc.fire (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:2:15151)
    at W (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:3:6340)
    at U0.invoke (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:2:14382)
    at Lc.fire (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:2:15151)
    at ub.fireClose (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:2:17406)
    at ChildProcess.<anonymous> (c:\Users\Administrator\.vscode\extensions\vue.volar-0.34.11-win32-x64\dist\node\client.js:29:12844)
    at ChildProcess.emit (node:events:402:35)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
`

VSCode Version: 1.66.2
Node.js: 16.13.0
OS: Windows_NT x64 10.0.18363

**Comment by luisnquin** [comment]
The same here, specifically when I open the `<template>` tag in Vue files.

**Comment by johnsoncodehk** [comment]
Seems you are using outdate version v0.34.1, please try update Volar and VSCode version.
