### ISSUE TITLE
TypeScript Auto Import Not Working in `*.vue` Files (Wrong Path?)

### ISSUE THREAD

**Issue by Tanimodori** [johnsoncodehk/volar#1310]
## Description
TypeScript auto import for `ref` in `Component.vue` not working:

```vue
<script lang='ts' setup>
const foo = ref(0)
</script>
```

The VSCode log claims that: (Note the `Component.vue.ts` part, the actual filename is `Component.vue`)

```
[2022-05-18 09:41:00.453] [renderer1] [error] 无法读取文件'c:\path\to\src\Component.vue.ts' (Error: 无法解析不存在的文件 'c:\path\to\src\Component.vue.ts'): Error: 无法读取文件'c:\path\to\src\Component.vue.ts' (Error: 无法解析不存在的文件 'c:\path\to\src\Component.vue.ts')
    at p.doReadFileStream (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:594:24262)
    at async f.doRead (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:42343)
    at async f.readStream (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:42018)
    at async ir.resolveFromFile (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2726:66754)
    at async u.doResolve (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:36878)
    at async c.acquire (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:17:32618)
    at async l.createModelReference (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2726:79578)
    at async Promise.all (index 0)
    at async i._createEditsTasks (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:894:20015)
    at async i.apply (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:894:20191)
    at async g._performTextEdits (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:28024)
    at async g.perform (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:27407)
    at async v.apply (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:29719)
    at async f (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:688:22077)
    at async Object.applyCodeAction (vscode-file://vscode-app/c:/Users/<user>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:688:20828)
```

## Environment

* VSCode: 1.67.1
* Volar v0.34.15

## Extra Info
* This feature has been working perfectly in the same project until I upgrade VSCode recently.
* This bug seems to be related with newly created `*.vue` files.

**Comment by johnsoncodehk** [comment]
Fixed by https://github.com/johnsoncodehk/volar/commit/768e64955556dbbb72ef7c77141e183e117bb582
