### ISSUE TITLE
Volar crashes when doing a .vue file rename

### ISSUE THREAD

**Issue by gregveres** [johnsoncodehk/volar#1866]
I copied a .vue file in my project and then I renamed it. 
The rename took about 30 seconds. When it finally completed, I received the following notifications:
```
Connection to server got closed. Server will not be restarted
```
```
Client Volar - Second Language Features Server: connection to server is erroring. Shutting down server.
```

I happen to have the dev tools open when I did this and here are the errors that came out on the console. 
During the 30 seconds I was waiting, nothing was coming out on the console, then when it finally finished, I received the notifications and the console errors at the same time.

```
[Extension Host] DocumentRecord Interval running for doc c:\Users\Greg\source\repos\SquashSpider\SquashSpider\SkyCourt.UI\skycourt\libs\domain\court-booking\admin\src\lib\reports\CourtReportTable.vue.git
notificationsAlerts.ts:42 Connection to server got closed. Server will not be restarted.
onDidChangeNotification @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
addNotification @ notifications.ts:204
notify @ notificationService.ts:175
(anonymous) @ mainThreadMessageService.ts:77
_showMessage @ mainThreadMessageService.ts:42
$showMessage @ mainThreadMessageService.ts:36
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
Show 2 more frames
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Pending response rejected since connection got disposed
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
console.ts:137 [Extension Host] stack trace: Error: Pending response rejected since connection got disposed
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:4501)
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:22382)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:12309)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:50712)
	at t (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:11990)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at U (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:3:6493)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at $y.fireClose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:17416)
	at ChildProcess.<anonymous> (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:13117)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
mainThreadExtensionService.ts:79 [[object Object]]Pending response rejected since connection got disposed
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
mainThreadExtensionService.ts:80 Error: Pending response rejected since connection got disposed
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:4501)
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:22382)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:12309)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:50712)
	at t (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:11990)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at U (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:3:6493)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at $y.fireClose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:17416)
	at ChildProcess.<anonymous> (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:13117)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Pending response rejected since connection got disposed
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
console.ts:137 [Extension Host] stack trace: Error: Pending response rejected since connection got disposed
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:4501)
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:22382)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:12309)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:50712)
	at t (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:11990)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at U (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:3:6493)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at $y.fireClose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:17416)
	at ChildProcess.<anonymous> (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:13117)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
mainThreadExtensionService.ts:79 [[object Object]]Pending response rejected since connection got disposed
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
mainThreadExtensionService.ts:80 Error: Pending response rejected since connection got disposed
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:4501)
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:22382)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:12309)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:50712)
	at t (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:11990)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at U (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:3:6493)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at $y.fireClose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:17416)
	at ChildProcess.<anonymous> (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:13117)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Pending response rejected since connection got disposed
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
console.ts:137 [Extension Host] stack trace: Error: Pending response rejected since connection got disposed
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:4501)
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:22382)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:12309)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:50712)
	at t (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:11990)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at U (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:3:6493)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at $y.fireClose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:17416)
	at ChildProcess.<anonymous> (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:13117)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
mainThreadExtensionService.ts:79 [[object Object]]Pending response rejected since connection got disposed
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
E @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
mainThreadExtensionService.ts:80 Error: Pending response rejected since connection got disposed
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:4501)
	at Object.dispose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:22382)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:12309)
	at $w.handleConnectionClosed (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:50712)
	at t (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:39:11990)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at U (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:3:6493)
	at yy.invoke (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:14392)
	at Ma.fire (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:15161)
	at $y.fireClose (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:2:17416)
	at ChildProcess.<anonymous> (c:\Users\Greg\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\client.js:29:13117)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess.emit (node:domain:475:12)
	at maybeClose (node:internal/child_process:1092:16)
	at ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by johnsoncodehk** [comment]
Could you try can this problem reproduce in https://github.com/johnsoncodehk/volar-starter?
