### ISSUE TITLE
[Crash] TypeError: Cannot read properties of null (reading 'validProperties')

### ISSUE THREAD

**Issue by Akryum** [johnsoncodehk/volar#1902]
I'm experiencing a lot of Volar server crashes lately.

Version: 1 alpha 4
Repo: https://github.com/vuejs/devtools

```
TypeError: Cannot read properties of null (reading 'validProperties')
    at TP.getSetting (/home/akryum/.vscode/extensions/vue.volar-1.0.0-alpha.4/dist/node/server.js:1008:14631)
    at new _p (/home/akryum/.vscode/extensions/vue.volar-1.0.0-alpha.4/dist/node/server.js:1008:18515)
    at _p.entries (/home/akryum/.vscode/extensions/vue.volar-1.0.0-alpha.4/dist/node/server.js:1008:18705)
    at gb.doValidation (/home/akryum/.vscode/extensions/vue.volar-1.0.0-alpha.4/dist/node/server.js:1008:26467)
    at Object.doValidation (/home/akryum/.vscode/extensions/vue.volar-1.0.0-alpha.4/dist/node/server.js:1057:10106)
    at Object.<anonymous> (/home/akryum/.vscode/extensions/vue.volar-1.0.0-alpha.4/dist/node/server.js:1057:11526)
    at Generator.next (<anonymous>)
    at o (/home/akryum/.vscode/extensions/vue.volar-1.0.0-alpha.4/dist/node/server.js:1057:9142)
[Error - 12:21:58 PM] The Volar - Second Language Features Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by johnsoncodehk** [comment]
Hi @Akryum, which file are you opening and then throwing the error? Could you provide your system info from `Help: About` command?

**Comment by Akryum** [comment]
My recently opened files:

![image](https://user-images.githubusercontent.com/2798204/192095232-97c351e8-bb9e-4193-a909-b47b7659c10b.png)


`Help: About`:

```Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.9-200.fc36.x86_64
Sandboxed: No```
