### ISSUE TITLE
Intellisense not working with vue files

### ISSUE THREAD

**Issue by TheInvoker** [johnsoncodehk/volar#1927]
I made a new vite3/vue3/vuetify3/typescript project. Installed VS code and volar extension. All latest version. But when I edit the vue files, I don't get any intellisense on the typescript. How can I resolve it?

**Comment by robmolloyntt** [comment]
This also the same for me

**Comment by johnsoncodehk** [comment]
Could you provide repro case?

**Comment by robmolloyntt** [comment]
I just ran `npm init vue@latest` and choosing typescript 'Yes', everything else 'No'.

**Comment by robmolloyntt** [comment]
```
<script setup lang="ts">
import { ref } from "vue";
import { group } from "src/...";
```

As I'm typing the file path I was expecting to see directory/file suggestions. Also no suggestions for relative paths.

**Comment by johnsoncodehk** [comment]
@robmolloyntt please add `"src/*": ["./src/*"],` to `compilerOptions.paths` in tsconfig, or use relative path instead of.

**Comment by robmolloyntt** [comment]
<img width="1264" alt="Screenshot 2022-10-05 at 04 18 06" src="https://user-images.githubusercontent.com/98746646/193973669-4d1b6748-b908-479c-8777-fc87b7059d5f.png">

I've just seen that I'm getting this eslint error displayed in vscode

**Comment by robmolloyntt** [comment]
<img width="1041" alt="Screenshot 2022-10-05 at 04 21 55" src="https://user-images.githubusercontent.com/98746646/193974250-54355612-3fc7-4472-98ce-2ab98a99f31a.png">

**Comment by robmolloyntt** [comment]
apologies @johnsoncodehk  I should have said that I have added compilerOptions.paths as suggested but it hasn't worked

**Comment by TheInvoker** [comment]
I get this

```
I get this

```
node:internal/bootstrap/switches/does_own_process_state:112
  rawMethods.chdir(directory);
             ^

Error: ENOENT: no such file or directory, chdir 'c:\Users\user\Documents\GitHub\CompanyDocumentationViewer' -> 'c:\Users\user\source\repos\GlobalReports'
    at process.wrappedChdir [as chdir] (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at Object.apply (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:20408)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29857
    at Generator.next (<anonymous>)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29461
    at new Promise (<anonymous>)
    at Xa (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29258)
    at owt (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29755)
    at Object.add (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:34421)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:17750 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: 'c:\\Users\\user\\Documents\\GitHub\\CompanyDocumentationViewer',
  dest: 'c:\\Users\\user\\source\\repos\\GlobalReports'
}
[Info  - 3:26:55 PM] Connection to server got closed. Server will restart.
node:internal/bootstrap/switches/does_own_process_state:112
  rawMethods.chdir(directory);
             ^

Error: ENOENT: no such file or directory, chdir 'c:\Users\user\Documents\GitHub\CompanyDocumentationViewer' -> 'c:\Users\user\source\repos\GlobalReports'
    at process.wrappedChdir [as chdir] (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at Object.apply (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:20408)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29857
    at Generator.next (<anonymous>)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29461
    at new Promise (<anonymous>)
    at Xa (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29258)
    at owt (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29755)
    at Object.add (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:34421)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:17750 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: 'c:\\Users\\user\\Documents\\GitHub\\CompanyDocumentationViewer',
  dest: 'c:\\Users\\user\\source\\repos\\GlobalReports'
}
[Info  - 3:27:11 PM] Connection to server got closed. Server will restart.
node:internal/bootstrap/switches/does_own_process_state:112
  rawMethods.chdir(directory);
             ^

Error: ENOENT: no such file or directory, chdir 'c:\Users\user\Documents\GitHub\CompanyDocumentationViewer' -> 'c:\Users\user\source\repos\GlobalReports'
    at process.wrappedChdir [as chdir] (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at Object.apply (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:20408)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29857
    at Generator.next (<anonymous>)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29461
    at new Promise (<anonymous>)
    at Xa (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29258)
    at owt (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29755)
    at Object.add (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:34421)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:17750 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: 'c:\\Users\\user\\Documents\\GitHub\\CompanyDocumentationViewer',
  dest: 'c:\\Users\\user\\source\\repos\\GlobalReports'
}
[Info  - 3:27:24 PM] Connection to server got closed. Server will restart.
node:internal/bootstrap/switches/does_own_process_state:112
  rawMethods.chdir(directory);
             ^

Error: ENOENT: no such file or directory, chdir 'c:\Users\user\Documents\GitHub\CompanyDocumentationViewer' -> 'c:\Users\user\source\repos\GlobalReports'
    at process.wrappedChdir [as chdir] (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at Object.apply (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:20408)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29857
    at Generator.next (<anonymous>)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29461
    at new Promise (<anonymous>)
    at Xa (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29258)
    at owt (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29755)
    at Object.add (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:34421)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:17750 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: 'c:\\Users\\user\\Documents\\GitHub\\CompanyDocumentationViewer',
  dest: 'c:\\Users\\user\\source\\repos\\GlobalReports'
}
[Info  - 3:27:36 PM] Connection to server got closed. Server will restart.
node:internal/bootstrap/switches/does_own_process_state:112
  rawMethods.chdir(directory);
             ^

Error: ENOENT: no such file or directory, chdir 'c:\Users\user\Documents\GitHub\CompanyDocumentationViewer' -> 'c:\Users\user\source\repos\GlobalReports'
    at process.wrappedChdir [as chdir] (node:internal/bootstrap/switches/does_own_process_state:112:14)
    at Object.apply (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:20408)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29857
    at Generator.next (<anonymous>)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29461
    at new Promise (<anonymous>)
    at Xa (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29258)
    at owt (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:29755)
    at Object.add (c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1291:34421)
    at c:\Users\user\.vscode\extensions\vue.volar-0.40.13-win32-x64\dist\node\server.js:1292:17750 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'chdir',
  path: 'c:\\Users\\user\\Documents\\GitHub\\CompanyDocumentationViewer',
  dest: 'c:\\Users\\user\\source\\repos\\GlobalReports'
}
[Error - 3:27:44 PM] The Volar - Language Features Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

```

```

**Comment by johnsoncodehk** [comment]
@TheInvoker please try v1.0.x, if still not working please provide minimal reproduction.

@Readpato you can try check tsconfig includes file use this plugin: https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-tsconfig-helper

**Comment by Readpato** [comment]
> @Readpato you can try check tsconfig includes file use this plugin: https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.vscode-tsconfig-helper

Thank you very much it solved my problem <3

**Comment by johnsoncodehk** [comment]
@TheInvoker please update the project vue-tsc version, and pin @types/node version to 18.8.0.

**Comment by armia-roma** [comment]
hi i get same error but i did not understand how to solve it can some help plz

**Comment by robMolloy** [comment]
@armia-roma Create a new Nuxt project, if you open the new project in vscode this should work.  If it doesn't try updating vscode, but I think this error has been fixed so it's likely a different one and should be raised as a new issue (only if it is definitely an issue, and not just an issue with your setup)
