### ISSUE TITLE
The Vue Semantic Server server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by vit112** [johnsoncodehk/volar#1957]
Volar extention was working perfectly fine until this error appeared out of the blue today. I tried reinstalling vscode and volar. Then I increased --max-old-space-size for node and maxTsServerMemory. However, the error still remains. 

VS code version 1.72.0
Volar version: v1.0.1
Ubuntu 22.04.1 LTS

[Info  - 10:57:15 PM] Connection to server got closed. Server will restart.
[Error - 10:57:16 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read properties of undefined (reading '0')
  Code: -32603 
[Error - 10:57:16 PM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read properties of undefined (reading '0')
  Code: -32603 
[Error - 10:57:16 PM] Request textDocument/inlayHint failed.
  Message: Request textDocument/inlayHint failed with message: Cannot read properties of undefined (reading '0')
  Code: -32603 
/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:41584
        var rootExpression = (_a = sourceFile.statements[0]) === null || _a === void 0 ? void 0 : _a.expression;
                                                        ^

TypeError: Cannot read properties of undefined (reading '0')
    at convertConfigFileToObject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:41584:57)
    at parseOwnConfigOfJsonSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:42411:20)
    at parseConfig (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:42307:13)
    at parseJsonConfigFileContentWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:42123:28)
    at Object.parseJsonSourceFileConfigFileContent (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:42086:22)
    at Object.mJ (/home/vt/.vscode/extensions/vue.volar-1.0.1-linux-x64/dist/node/server.js:841:3875)
    at Object.resolveLanguageServiceHost (/home/vt/.vscode/extensions/vue.volar-1.0.1-linux-x64/dist/node/server.js:1119:12428)
    at S (/home/vt/.vscode/extensions/vue.volar-1.0.1-linux-x64/dist/node/server.js:496:29747)
    at /home/vt/.vscode/extensions/vue.volar-1.0.1-linux-x64/dist/node/server.js:496:27227
    at Generator.next (<anonymous>)
[Error - 10:57:16 PM] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by johnsoncodehk** [comment]
It seems failed at https://github.com/johnsoncodehk/volar/blob/627a3ab84165cd851b471a8350d77f608612dc43/vue-language-tools/vue-language-core/src/utils/ts.ts#L32, I guess you have some tsconfig files it's empty or invalid jsonc format. I will check how to fault tolerance with it, you and try to check tsconfig content you have.

**Comment by vit112** [comment]
Many thanks for the reply John. 

You are right, there seems to be an invalid path under references in tsconfig. It does not crash after fixing that. Strangely enough, it did not cause any issues earlier.

**Comment by johnsoncodehk** [comment]
This error is ignore by try catch in old version, I kind of want to keep this crash, otherwise when failed users just loses all intellisense without any hints. I will keep this issue open for more time to thinking.

**Comment by totalhack** [comment]
I got this error because I switched the name of a directory that was a workspace in vs code.

**Comment by prd-quy-nguyen** [comment]
I got this problem after setup pnpm. I am not sure if it is related to pnpm or not but I cannot fix it
