### ISSUE TITLE
Connection to server got closed. Server will restart.

### ISSUE THREAD

**Issue by delayhsiao** [johnsoncodehk/volar#2186]
hello, i has an error with volar plugin in vscode.
my vue version is 2, it worked before,but i update vscode and volar plugin lately. now, when i start vscode and open .vue file, i found the error info in console, and editor cannot work normally, i readed all questions and answers in github's issues channel,but always cannot found the resolve way, i cannot work with volar,please help me resolve this question,thx
i tried to fallback vscode and volar's version, but is not works. or i guess i need to change typescript's version?but i didn't use typescript,does it have any relations? @johnsoncodehk 
```
[Info  - 15:41:26] Connection to server got closed. Server will restart.
node:buffer:594
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (node:buffer:594:37)
    at Buffer.toString (node:buffer:812:14)
    at readFileWorker (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:7519:31)
    at Proxy.readFile (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:7523:28)
    at Object.apply (c:\Users\QianManage\.vscode\extensions\vue.volar-1.0.12-win32-x64\dist\node\server.js:495:27020)
    at Object.J [as getScriptSnapshot] (c:\Users\QianManage\.vscode\extensions\vue.volar-1.0.12-win32-x64\dist\node\server.js:494:31455)
    at Proxy.getScriptSnapshot (c:\Users\QianManage\.vscode\extensions\vue.volar-1.0.12-win32-x64\dist\node\server.js:992:1124)
    at p (c:\Users\QianManage\.vscode\extensions\vue.volar-1.0.12-win32-x64\dist\node\server.js:490:26815)
    at Object.get (c:\Users\QianManage\.vscode\extensions\vue.volar-1.0.12-win32-x64\dist\node\server.js:490:26320)
    at Object.createLanguageService (c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:167546:38) {
  code: 'ERR_STRING_TOO_LONG'
}
[Error - 15:41:35] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by johnsoncodehk** [comment]
It seem that typescript try to read a file that large than 512MB.

Can you can try open c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:7523:28 and print the file path to see what's is that file?

**Comment by delayhsiao** [comment]
> It seem that typescript try to read a file that large than 512MB.
> 
> Can you can try open c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\typescript.js:7523:28 and print the file path to see what's is that file?

yes,i printed the file path and it's my asset file in dist directory. so how can i ignore the file?
@johnsoncodehk

**Comment by delayhsiao** [comment]
so is it haven't any method to ignore specific files? @johnsoncodehk

**Comment by johnsoncodehk** [comment]
Please try 1.0.14 when it released.
