### ISSUE TITLE
[error] Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by jamaluddinrumi** [johnsoncodehk/volar#2201]
**Environment** 
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.18.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.18.2`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`
- Build Modules:    `-`
------------------------------

**VSCode**
------------------------------
- Version: 1.74.0 (Universal)
- Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
- Date: 2022-12-05T16:43:37.594Z
- Electron: 19.1.8
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Darwin x64 17.7.0
- Sandboxed: No
------------------------------

**VSCode Error Log**
------------------------------
```
2022-12-13 21:39:29.317 [error] Corrupt ZIP: end of central directory record signature not found: CorruptZip: Corrupt ZIP: end of central directory record signature not found
    at z.p (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:162859)
    at async z.extractUserExtension (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:160555)
    at async Y.q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:166093)
    at async Y.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:167256)
2022-12-13 21:42:44.782 [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {"name":"Canceled"}
```
------------------------------

i use ubuntu for my development connected to my mac via ssh 
i can not install Volar as shown screenshot below
![Screen Shot 2022-12-13 at 9 42 14 PM](https://user-images.githubusercontent.com/446780/207365868-620e3406-6662-4985-ba1b-b16c8050e8ad.png)
but, i can install Vetur
![Screen Shot 2022-12-13 at 9 43 33 PM](https://user-images.githubusercontent.com/446780/207366153-8e8384f4-73ee-430c-a44b-358ba65ada5f.png)

**Comment by johnsoncodehk** [comment]
Can you try "Try Downloading Manually..."? If still not working please provide the .visx file that you have downloaded.

**Comment by jamaluddinrumi** [comment]
i don't know what i'm changing yesterday but it's already can be installed (v1.0.16)

you are welcome to close this issue. thanks john for your follow up.
