### ISSUE TITLE
Volar will fail to start preview server if `.vite` directory doesn't exist yet.

### ISSUE THREAD

**Issue by segevfiner** [johnsoncodehk/volar#2223]
```
node "/Users/segevfiner/.vscode/extensions/vue.volar-1.0.14-darwin-arm64/dist/preview-bin/vite.js" --port=3333
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/segevfiner/junk/volar-starter/node_modules/.vite/volar-vite.config.ts'
    at Object.openSync (node:fs:590:3)
    at Object.writeFileSync (node:fs:2202:35)
    at createViteConfig (/Users/segevfiner/.vscode/extensions/vue.volar-1.0.14-darwin-arm64/dist/preview-bin/vite.js:90:5)
    at Object.<anonymous> (/Users/segevfiner/.vscode/extensions/vue.volar-1.0.14-darwin-arm64/dist/preview-bin/vite.js:76:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/segevfiner/junk/volar-starter/node_modules/.vite/volar-vite.config.ts'
```

**Comment by johnsoncodehk** [comment]
We currently do not check this, a workaround is run `npm run dev` for vite project before the preview feature.
https://github.com/johnsoncodehk/volar/blob/087f0faac321b01575232b647675179954447408/packages/preview/bin/vite.js#L85-L93

**Comment by segevfiner** [comment]
Yeah. That's what I did, still might want to stick an `mkdir` there, no?

**Comment by johnsoncodehk** [comment]
Maybe automatically execute `npm run dev` for the project to build the .vite, or pop up a prompt asking the user to do so. 🤔(Not sure the best solution for now.)

**Comment by segevfiner** [comment]
Why not just an `mkdir`? Do you actually need the contents of that directory or just a place to put `volar-vite.config.ts`?

**Comment by johnsoncodehk** [comment]
Maybe you're right, I sort of forgot how that was done, will see later.
