### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Shinigami92** [johnsoncodehk/volar#231]
When I'm building my project I'm getting an error
This happend between these commits: https://github.com/Shinigami92/vizscript/compare/c3d26fd3f921787dab0bf25cb9d024d170824225...main
Before two days it worked

```node
yarn run v1.22.10
$ vue-tsc --noEmit && vite build
/home/shinigami/OpenSource/vizscript/node_modules/vscode-vue-languageservice/out/sourceFile.js:332
            return name.indexOf('$') === -1 && !name.startsWith('_');
                        ^

TypeError: Cannot read property 'indexOf' of undefined
    at /home/shinigami/OpenSource/vizscript/node_modules/vscode-vue-languageservice/out/sourceFile.js:332:25
    at Array.filter (<anonymous>)
    at updateTemplateScript (/home/shinigami/OpenSource/vizscript/node_modules/vscode-vue-languageservice/out/sourceFile.js:330:33)
    at Object.updateTemplateScript (/home/shinigami/OpenSource/vizscript/node_modules/vscode-vue-languageservice/out/sourceFile.js:917:28)
    at updateSourceFiles (/home/shinigami/OpenSource/vizscript/node_modules/vscode-vue-languageservice/out/languageService.js:503:89)
    at update (/home/shinigami/OpenSource/vizscript/node_modules/vscode-vue-languageservice/out/languageService.js:327:17)
    at Object.apply (/home/shinigami/OpenSource/vizscript/node_modules/vscode-vue-languageservice/out/languageService.js:253:21)
    at emitFilesAndReportErrors (/home/shinigami/OpenSource/vizscript/node_modules/vue-tsc/typescript/lib/tsc.js:92266:45)
    at Object.emitFilesAndReportErrorsAndGetExitStatus (/home/shinigami/OpenSource/vizscript/node_modules/vue-tsc/typescript/lib/tsc.js:92301:18)
    at performCompilation (/home/shinigami/OpenSource/vizscript/node_modules/vue-tsc/typescript/lib/tsc.js:94775:29)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

https://github.com/johnsoncodehk/volar/blob/c748e854b67cdcb00b2746baf44a83e06c1debcf/packages/vscode-vue-languageservice/src/sourceFile.ts#L387

Reproducible: https://github.com/Shinigami92/vizscript/tree/fb83eecf01e651f56060ceb1f80fbfefd1fbbf80

**Comment by johnsoncodehk** [comment]
Fixed in `vue-tsc@0.1.7` with `vscode-language-service@0.25.18`.
