### ISSUE TITLE
There is a problem with CodeLens (setup sugar) in "v0.27.4"

### ISSUE THREAD

**Issue by yaegassy** [johnsoncodehk/volar#397]
## Capture (mp4)

https://user-images.githubusercontent.com/188642/130305329-9db0f72c-7715-4391-8887-aa211863a17a.mp4

## Error

```
[Error - 10:01:29] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with message: Cannot read property 'loc' of null
  Code: -32603 
(node:74853) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'loc' of null
    at getAddMissingImportsEdits (/Users/yaegassy/.vscode/extensions/johnsoncodehk.volar-0.27.4/node_modules/vscode-vue-languageservice/out/commands/useSetupSugar.js:40:57)
    at /Users/yaegassy/.vscode/extensions/johnsoncodehk.volar-0.27.4/node_modules/vscode-vue-languageservice/out/commands/useSetupSugar.js:32:39
    at async Object.<anonymous> (/Users/yaegassy/.vscode/extensions/johnsoncodehk.volar-0.27.4/node_modules/vscode-vue-languageservice/out/services/executeCommand.js:26:13)
(Use `Code Helper (Renderer) --trace-warnings ...` to show where the warning was created)
(node:74853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:74853) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:74853) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'loc' of null
    at getAddMissingImportsEdits (/Users/yaegassy/.vscode/extensions/johnsoncodehk.volar-0.27.4/node_modules/vscode-vue-languageservice/out/commands/useSetupSugar.js:40:57)
    at /Users/yaegassy/.vscode/extensions/johnsoncodehk.volar-0.27.4/node_modules/vscode-vue-languageservice/out/commands/useSetupSugar.js:32:39
    at async Object.<anonymous> (/Users/yaegassy/.vscode/extensions/johnsoncodehk.volar-0.27.4/node_modules/vscode-vue-languageservice/out/services/executeCommand.js:26:13)
(node:74853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:74853) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'loc' of null
    at getAddMissingImportsEdits (/Users/yaegassy/.vscode/extensions/johnsoncodehk.volar-0.27.4/node_modules/vscode-vue-languageservice/out/commands/useSetupSugar.js:40:57)
    at /Users/yaegassy/.vscode/extensions/johnsoncodehk.volar-0.27.4/node_modules/vscode-vue-languageservice/out/commands/useSetupSugar.js:32:39
    at async Object.<anonymous> (/Users/yaegassy/.vscode/extensions/johnsoncodehk.volar-0.27.4/node_modules/vscode-vue-languageservice/out/services/executeCommand.js:26:13)
(node:74853) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[Error - 10:01:29] Request textDocument/semanticTokens/range failed.
  Message: Request textDocument/semanticTokens/range failed with message: Cannot read property 'loc' of null
  Code: -32603 
[Error - 10:01:29] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed with message: Cannot read property 'loc' of null
  Code: -32603 
[Error - 10:01:30] Request textDocument/semanticTokens/range failed.
  Message: Request textDocument/semanticTokens/range failed with message: Cannot read property 'loc' of null
  Code: -32603 
[Error - 10:01:30] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read property 'loc' of null
  Code: -32603 
[Error - 10:01:34] Request textDocument/codeLens failed.
  Message: Request textDocument/codeLens failed with message: Cannot read property 'loc' of null
  Code: -32603 
```

**Comment by cdlaiqi** [comment]
I'm in the same situation as you，back to v0.27.3 is ok

**Comment by johnsoncodehk** [comment]
Thanks in 0.27.5, thanks for the report!

**Comment by Half-A-Turnip** [comment]
@johnsoncodehk back to v0.27.3 is ok,but v0.27.5  is no。thanks


https://user-images.githubusercontent.com/24860389/130316241-f01a0e14-744d-4bb4-800d-a1e8e2a0926f.mp4

**Comment by johnsoncodehk** [comment]
@Half-A-Turnip Could you try to run debug mode with this commit? https://github.com/johnsoncodehk/volar/commit/df2a3acb031c69fb894ce138ff61730bb2c7e33b

Run debug mode: https://github.com/johnsoncodehk/volar/blob/master/.github/STEP_TO_PROFILING.md#run-volar-on-debug-mode

**Comment by Half-A-Turnip** [comment]
@

> @Half-A-Turnip Please try v0.27.6.

@johnsoncodehk i tried. latest branch is ok. now 0.27.6 is good. thanks

**Comment by TrayHard** [comment]
v0.34.11 and having the same problem over here

**Comment by johnsoncodehk** [comment]
@TrayHard Please check if you can update your vscode version, if you can't fix please open a new issue and describe your error.
