### ISSUE TITLE
Error : Request textDocument/codeLens failed with message: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jamols09** [johnsoncodehk/volar#474]
Hello I got a tons of error on my device upon checking the output terminal. I'm not sure how to fix this entirely.

This is on the PC
```
[Error - 5:38:49 PM] Request textDocument/semanticTokens/range failed.
  Message: Request textDocument/semanticTokens/range failed with message: Cannot read property 'length' of undefined
  Code: -32603 
```
Laptop

![image](https://user-images.githubusercontent.com/20100579/132664541-ff5fd7d8-ff18-4059-aec0-287f7a0720ca.png)

It looks like the error are somewhat related to each other.

**Comment by jiangmaniu** [comment]
+1, it seems to be caused by the `v0.27.17` version, I tried to roll back the version to `v0.27.16` and it works normally

**Comment by iamanewofkotlin** [comment]
I have encountered same. but i just updates version of ``typescript`` to ``4.4.2``. The question was fixed.

**Comment by jamols09** [comment]
> +1, it seems to be caused by the `v0.27.17` version, I tried to roll back the version to `v0.27.16` and it works normally

Hello, how do I perform rollback on an extension?

**Comment by iamanewofkotlin** [comment]
> > +1, it seems to be caused by the `v0.27.17` version, I tried to roll back the version to `v0.27.16` and it works normally
> 
> How do I perform rollback on an extension?

Visiting VSCode marketplace [VSCode marketplace](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar), and then clicking ``history version``, and then downloading ``v0.27.16``, finally find downloaded file, Dragging it  into  window of VScode ``extension``.

**Comment by mkhennoussi** [comment]
Still present in v0.27.18

**Comment by johnsoncodehk** [comment]
> Still present in v0.27.18

Can you provide repro case.

**Comment by mkhennoussi** [comment]
I just use the vitesse template : https://github.com/antfu/vitesse

**Comment by johnsoncodehk** [comment]
> I just use the vitesse template : https://github.com/antfu/vitesse

Can't reproduce, what do I need to do in template?

**Comment by stafyniaksacha** [comment]
@jamols09 on vuero ?

**Comment by jamols09** [comment]
> @jamols09 on vuero ?

Nope, the extension just got bugged. Does show error on any projects but I think this is fixed already.

**Comment by iamanewofkotlin** [comment]
@johnsoncodehk
When i building my project. Throwing an error 
```
$ vue-tsc --noEmit && vite build
/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:17
                    result.push({ start: offset, end: offset + matchText.length });
                                                                         ^

TypeError: Cannot read property 'length' of undefined
    at visChild (/Users/zc/projects/apollov-setup/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:17:74)
    at visChild (/Users/zc/projects/apollov-setup/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:23:17)
    at visChild (/Users/zc/projects/apollov-setup/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:23:17)
    at visChild (/Users/zc/projects/apollov-setup/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:23:17)
    at visChild (/Users/zc/projects/apollov-setup/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:23:17)
    at parse (/Users/zc/projects/apollov-setup/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:6:5)
    at ReactiveEffect.fn (/Users/zc/projects/apollov-setup/node_modules/vscode-vue-languageservice/out/use/useSfcStyles.js:31:58)
    at ReactiveEffect.run (/Users/zc/projects/apollov-setup/node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)
    at ComputedRefImpl.get value [as value] (/Users/zc/projects/apollov-setup/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1076:39)
    at ReactiveEffect.fn (/Users/zc/projects/apollov-setup/node_modules/vscode-vue-languageservice/out/use/useSfcTemplateScript.js:22:116)
error Command failed with exit code 1.
                                ^
```

Because i have a segment of code like this;
```vue
<script lang="ts" setup>
const style = { foo: 'bar', color: '#101010' }
</script>

<style>
.bg-color: v-bind(style.color);
</style>
```

Shall we creating an issue to ``vscode-vue-languageservice``?

**Comment by iamanewofkotlin** [comment]
@johnsoncodehk 

When i building my project. Throwing an error 
```
$ vue-tsc --noEmit && vite build
/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:17
                    result.push({ start: offset, end: offset + matchText.length });
                                                                         ^

TypeError: Cannot read property 'length' of undefined
    at visChild (/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:17:74)
    at visChild (/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:23:17)
    at visChild (/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:23:17)
    at visChild (/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:23:17)
    at visChild (/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:23:17)
    at parse (/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/parsers/cssBinds.js:6:5)
    at ReactiveEffect.fn (/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/use/useSfcStyles.js:31:58)
    at ReactiveEffect.run (/Users/zc/projects/foo/node_modules/@vue/reactivity/dist/reactivity.cjs.js:164:29)
    at ComputedRefImpl.get value [as value] (/Users/zc/projects/foo/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1076:39)
    at ReactiveEffect.fn (/Users/zc/projects/foo/node_modules/vscode-vue-languageservice/out/use/useSfcTemplateScript.js:22:116)
error Command failed with exit code 1.
                                ^
```

Because i have a segment of code like this;
```vue
<script lang="ts" setup>
const style = { foo: 'bar', color: '#101010' }
</script>

<style>
.bg-color: v-bind(style.color);
</style>
```

Shall we creating an issue to ``vscode-vue-languageservice``?

**Comment by johnsoncodehk** [comment]
@iamanewofkotlin please provide a minimum reproduce in a new issue with valid css code. Otherwise I can't check the problem, thank you.
