### ISSUE TITLE
After npm install no node.js file exist

### ISSUE THREAD

**Issue by jadestrong** [johnsoncodehk/volar#695]
May your publish only include `out` and `bin` .
`npm install -g @volar/server`
```
  drwxr-xr-x   3 jadestrong staff   96 Nov 13 20:15 bin
  drwxr-xr-x 329 jadestrong staff  11K Nov 13 20:15 node_modules
  drwxr-xr-x  24 jadestrong staff  768 Nov 13 20:15 out
  -rw-r--r--   1 jadestrong staff 1.1K Nov 13 20:15 LICENSE
  -rw-r--r--   1 jadestrong staff  745 Nov 13 20:15 package.json

```

**Comment by jadestrong** [comment]
```
npm install -g @volar/server

volar-server --version
```
throw error:
```
nternal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '../node.js'
Require stack:
- /Users/jadestrong/.nvm/versions/node/v14.17.4/lib/node_modules/@volar/server/bin/volar-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/jadestrong/.nvm/versions/node/v14.17.4/lib/node_modules/@volar/server/bin/volar-server.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jadestrong/.nvm/versions/node/v14.17.4/lib/node_modules/@volar/server/bin/volar-server.js'
  ]
}
```
