### ISSUE TITLE
Crash with `Cannot read property '0' of undefined` if typescript project references are used

### ISSUE THREAD

**Issue by ThaDaVos** [johnsoncodehk/volar#712]
As I am developing an App and a Proxy Server and I have shared types between the two, I've setup my monorepo according to the Typescript Project References documentation: https://www.typescriptlang.org/docs/handbook/project-references.html

But as soon as I add my `references` to the vue apps `tsconfig.json` - Volar starts crashing with `Cannot read property '0' of undefined` until I remove it again

```Shell
(node:26824) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at convertConfigFileToObject (/home/dylan/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/typescript.js:39654:57)
    at parseOwnConfigOfJsonSourceFile (/home/dylan/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/typescript.js:40449:20)
    at parseConfig (/home/dylan/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/typescript.js:40349:13)
    at parseJsonConfigFileContentWorker (/home/dylan/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/typescript.js:40168:28)
    at Object.parseJsonSourceFileConfigFileContent (/home/dylan/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/extensions/node_modules/typescript/lib/typescript.js:40135:16)
    at Object.createParsedCommandLine (/home/dylan/.vscode-server/extensions/johnsoncodehk.volar-0.29.5/node_modules/@volar/shared/out/ts.js:120:24)
    at createParsedCommandLine (/home/dylan/.vscode-server/extensions/johnsoncodehk.volar-0.29.5/node_modules/@volar/server/out/project.js:225:27)
    at createProject (/home/dylan/.vscode-server/extensions/johnsoncodehk.volar-0.29.5/node_modules/@volar/server/out/project.js:42:29)
    at async getParsedCommandLine (/home/dylan/.vscode-server/extensions/johnsoncodehk.volar-0.29.5/node_modules/@volar/server/out/projects.js:284:29)
    at async getReferencesChains (/home/dylan/.vscode-server/extensions/johnsoncodehk.volar-0.29.5/node_modules/@volar/server/out/projects.js:271:60)
(node:26824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```

Am I doing something wrong? Or are Typescript Project References not yet supported?

**Comment by johnsoncodehk** [comment]
Thanks for the report, but I can't reproduce this problem, could you provide repro case?

**Comment by ThaDaVos** [comment]
I'll try to setup a simple repo later - can't really share business code, can I 😂

**Comment by ThaDaVos** [comment]
The error seems to originate from here:
https://github.com/microsoft/TypeScript/blob/ae582a22ee1bb052e19b7c1bc4cac60509b574e0/src/compiler/commandLineParser.ts#L1957

Haven't set up the example repo yet - will do that shortly

**Comment by ThaDaVos** [comment]
Here is the repro repository - the `app` is a simple vue app created using the vue-cli - so open the folder and run `npm install`
After doing so, open one of the `.vue` files and see `Volar` error:

https://github.com/ThaDaVos/volar-undefined-0

**Comment by johnsoncodehk** [comment]
I can confirm this problem, thanks!

**Comment by johnsoncodehk** [comment]
You can change `"references": [ { "path": "../global" } ]` to `"references": [ { "path": "../global/tsconfig.json" } ]` as quick fix.

**Comment by ThaDaVos** [comment]
Your workaround works perfectly - still curious as to how it breaks - as it seems to break internally inside Typescript itself
