### ISSUE TITLE
node12 run command vue-tsc error

### ISSUE THREAD

**Issue by CodingDoll** [johnsoncodehk/volar#737]
using npm@6.14.15
using node@v12.22.7
```
\node_modules\vscode-jsonrpc\lib\common\linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)  
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\Dode\PLAYGROUND\dl-vue-vite\node_modules\vscode-jsonrpc\lib\common\api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)        
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
It is shown when the version of  `vscode-jsonrpc` is `8.0.0-next.4`. When I downgraded it to `8.0.0-next.3`, the problem is solved, but another similar problem come up that the version of `vscode-languageserver` is also too high.

**Comment by johnsoncodehk** [comment]
Please report to https://github.com/microsoft/vscode-languageserver-node.

We are using the latest lsp features, so we need the next version of vscode-languageserver.

**Comment by AHIMOTU** [comment]
It seems to be the Node version, node14+ is required. [https://hub.fastgit.org/microsoft/vscode-languageserver-node/issues/861](https://hub.fastgit.org/microsoft/vscode-languageserver-node/issues/861)
