### ISSUE TITLE
Request textDocument/documentLink failed

### ISSUE THREAD

**Issue by glen-84** [johnsoncodehk/volar#747]
```
[Error - 11:57:44] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read property '0' of undefined
  Code: -32603 
(node:18968) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at convertConfigFileToObject (d:\Programming\Projects\x\v4\api\node_modules\typescript\lib\tsserverlibrary.js:40022:57)
    at parseOwnConfigOfJsonSourceFile (d:\Programming\Projects\x\v4\api\node_modules\typescript\lib\tsserverlibrary.js:40839:20)
    at parseConfig (d:\Programming\Projects\x\v4\api\node_modules\typescript\lib\tsserverlibrary.js:40735:13)
    at parseJsonConfigFileContentWorker (d:\Programming\Projects\x\v4\api\node_modules\typescript\lib\tsserverlibrary.js:40554:28)
    at Object.parseJsonSourceFileConfigFileContent (d:\Programming\Projects\x\v4\api\node_modules\typescript\lib\tsserverlibrary.js:40521:16)
    at createParsedCommandLine (c:\Users\Glen\.vscode\extensions\johnsoncodehk.volar-0.29.7\node_modules\@volar\shared\out\ts.js:121:24)
    at Object.createParsedCommandLine (c:\Users\Glen\.vscode\extensions\johnsoncodehk.volar-0.29.7\node_modules\@volar\shared\out\ts.js:130:30)
    at createParsedCommandLine (c:\Users\Glen\.vscode\extensions\johnsoncodehk.volar-0.29.7\node_modules\@volar\server\out\project.js:226:27)
    at createProject (c:\Users\Glen\.vscode\extensions\johnsoncodehk.volar-0.29.7\node_modules\@volar\server\out\project.js:42:29)
```

```
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

Volar: v0.29.7

v0.29.6 does not have this issue.

**Comment by johnsoncodehk** [comment]
Could you show your tsconfig content?

**Comment by glen-84** [comment]
```jsonc
{
    "extends": "@company/tsconfig",
    "compilerOptions": {
        "baseUrl": ".",
        // https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#vuejs
        "importsNotUsedAsValues": "preserve",
        "lib": ["dom", "dom.iterable", "ES2020.Intl"],
        "module": "ESNext",
        "moduleResolution": "Node",
        "paths": {"@/*": ["./src/*"], "@icons/*": ["./src/app/core/assets/images/icons"]},
        "rootDir": "src",
        "target": "ES2017",
        "tsBuildInfoFile": "./node_modules/.cache/.tsbuildinfo"
    },
    "include": ["src/**/*", "types.d.ts"]
}
```

`@company/tsconfig`
```jsonc
{
    "compilerOptions": {
        "allowUnreachableCode": false,
        "emitDecoratorMetadata": true,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "forceConsistentCasingInFileNames": true,
        "importHelpers": true,
        "importsNotUsedAsValues": "error",
        "incremental": true,
        "newLine": "LF",
        "noImplicitOverride": true,
        "noImplicitReturns": true,
        "noPropertyAccessFromIndexSignature": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "resolveJsonModule": true,
        "skipLibCheck": true,
        "sourceMap": true,
        "strict": true
    }
}
```

Note: This is in an npm workspace (`client`), so a subdirectory off the root of the project.

**Comment by NikhilVerma** [comment]
I am having the same issue. I am also using the `extends` option of tsconfig.

Default config: tsconfig.default.json

```json
{
	"compilerOptions": {
		"allowJs": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"importHelpers": true,
		"jsx": "preserve",
		"lib": ["esnext", "dom", "dom.iterable", "scripthost"],
		"module": "esnext",
		"moduleResolution": "node",
		"noEmit": true,
		"noImplicitAny": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true,
		"target": "esnext",
		"types": ["node", "jest"]
	},
	"vueCompilerOptions": {
		"experimentalCompatMode": 2,
		"experimentalTemplateCompilerOptions": {
			"compatConfig": { "Mode": 2 }
		}
	}
}
```

Base tsconfig

```json
{
	"extends": "tsconfig.default.json",
	"compilerOptions": {
		"baseUrl": ".",
		"paths": {
			"@/*": ["src/*"]
		}
	},
	"include": ["src/**/*.ts", "src/**/*.tsx", "src/**/*.vue", "src/**/*.js"],
	"exclude": ["node_modules", "dist", ".yarn", "coverage"]
}
```

**Comment by NikhilVerma** [comment]
@johnsoncodehk I can confirm that when I remove extends and merge the config manually this problem seems to resolve itself.

**Comment by soulsam480** [comment]
Having same issue from this morning

**Comment by sullyD64** [comment]
Having the same issue, seems related to v0.29.7. I am also using `extends` in tsconfig since i'm working in a monorepo with multiple tsconfigs.
Rolling back to v0.29.6 solved it.

**Comment by iggith** [comment]
Same with scaffolded Quasar application, manual merge/rolling back to 0.29.6 solves it.

Generated application by default extends configuration of the framework with the initial base tsconfig:

```json
{
  "extends": "@quasar/app/tsconfig-preset",
  "compilerOptions": {
    "baseUrl": "."
  }
}
```

[tsconfig-preset](https://github.com/quasarframework/quasar/blob/fce5f189ec28711b911331a349df036ca0e5f4c9/app/tsconfig-preset.json)

**Comment by lkurylo** [comment]
Is it already resolved?
I have the same problem. In addition I see 
`Error: Cannot find module '../../../tsconfig.base.json'
Require stack:
- /home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/shared/out/ts.js
- /home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/shared/out/index.js
- /home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/common.js
- /home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/index.js
- /home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/node.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.createParsedCommandLine (/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/shared/out/ts.js:120:41)
    at createParsedCommandLine (/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/project.js:224:27)
    at createProject (/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/project.js:43:29)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processTimers (internal/timers.js:494:9)
    at async getParsedCommandLine (/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/projects.js:316:29)
    at async getReferencesChains (/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/projects.js:303:60)
    at async findTsconfig (/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/projects.js:266:36) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/shared/out/ts.js',
    '/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/shared/out/index.js',
    '/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/common.js',
    '/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/index.js',
    '/home/node/.vscode-server/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/node.js'
  ]
}`
I have Volar version 0.31.1. Can't believe this is still unfixed after all these months. Having base tsconfig file is popular in monorepo/shared in npm workspaces.
