### ISSUE TITLE
Crash with `Cannot read property '0' of undefined`

### ISSUE THREAD

**Issue by Aryess** [johnsoncodehk/volar#749]
It seems like the fix to #712 did introduce the same behaviour in other cases.

Here's a test repo: https://github.com/Aryess/testvolar, which was created using Quasar-cli (no code was modified).

- run `npm install`
- Open the repo in VS Code
- Install Volar
- Run Volar verify:
  - Using Volar 0.29.6:
![Screenshot from 2021-11-30 13-20-56](https://user-images.githubusercontent.com/3518172/143974824-248567d0-799e-4bad-9bd6-26996e7529cb.png)
  - Using Volar 0.29.7:
![Screenshot from 2021-11-30 13-21-30](https://user-images.githubusercontent.com/3518172/143974860-cd0447bc-6bd9-4c0b-952b-b4a3c667d0b0.png)
```
[Error - 1:21:19 PM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Cannot read property '0' of undefined
  Code: -32603 
(node:486686) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at convertConfigFileToObject (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:39654:57)
    at parseOwnConfigOfJsonSourceFile (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:40449:20)
    at parseConfig (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:40349:13)
    at parseJsonConfigFileContentWorker (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:40168:28)
    at Object.parseJsonSourceFileConfigFileContent (/usr/share/code/resources/app/extensions/node_modules/typescript/lib/typescript.js:40135:16)
    at createParsedCommandLine (/home/aryess/.vscode/extensions/johnsoncodehk.volar-0.29.7/node_modules/@volar/shared/out/ts.js:121:24)
    at Object.createParsedCommandLine (/home/aryess/.vscode/extensions/johnsoncodehk.volar-0.29.7/node_modules/@volar/shared/out/ts.js:130:30)
    at createParsedCommandLine (/home/aryess/.vscode/extensions/johnsoncodehk.volar-0.29.7/node_modules/@volar/server/out/project.js:226:27)
    at createProject (/home/aryess/.vscode/extensions/johnsoncodehk.volar-0.29.7/node_modules/@volar/server/out/project.js:42:29)
(Use `code --trace-warnings ...` to show where the warning was created)
(node:486686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by Li-Ninja** [comment]
I have same problem.
