### ISSUE TITLE
Error: Cannot find module './dist/shared.cjs.prod.js'

### ISSUE THREAD

**Issue by pontakornth** [johnsoncodehk/volar#915]
I am not sure if it is related to `pnpm` or not because it's also crash on React project. I tried to search the issue but I can't find similar issues or I didn't know the correct keyword to use.

```
internal/modules/cjs/loader.js:937
  throw err;
  ^

Error: Cannot find module './dist/shared.cjs.prod.js'
Require stack:
- /Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/@vue/shared/index.js
- /Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/vscode-vue-languageservice/out/services/semanticTokens.js
- /Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/vscode-vue-languageservice/out/index.js
- /Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/common.js
- /Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/index.js
- /Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/node.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/@vue/shared/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/@vue/shared/index.js',
    '/Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/vscode-vue-languageservice/out/services/semanticTokens.js',
    '/Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/vscode-vue-languageservice/out/index.js',
    '/Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/common.js',
    '/Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/out/index.js',
    '/Users/pontakornth/.vscode/extensions/johnsoncodehk.volar-0.31.1/node_modules/@volar/server/node.js'
  ]
}
```

This is the output from VSCode. HTML, document and API output similar errors.

## System Information
Volar: 0.31.1
NPM: 8.1.2
PNPM: 6.23.6
Node: 16.0.0

**Comment by pontakornth** [comment]
@johnsoncodehk


It occurs randomly so I don't know how to reproduce it. Do you have any suggestion?


BTW I tried to restart the language server. It said "command 'volar.action.restartServer' not found". I think it might be related.

**Comment by johnsoncodehk** [comment]
Although I don't know how this problem happen, I just fixed it in https://github.com/johnsoncodehk/volar/commit/3dcdb27742c7238acb62d6edf4e096093d8300bb, even it make the install package bigger.
